name: 01 - Building Blocks
on:
  pull_request:
    types:
      - closed
    branches:
      - main
      
  workflow_dispatch:

jobs:
  pr-merged:
    if: github.event.pull_request.merged == true && startsWith(github.head_ref, 'feature**')
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "PR is merged from a feature branch!"

  echo-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Hello, World!"  

  echo-goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: Failed step
        run: |
          echo "I will fail"
          exit 0

      - name: Say Bye
        run: echo "GoodBye!"