name: 04 - Using Actions
on:
    workflow_dispatch:
    push:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v7
              with:
                repository: ${{ github.repository }}
                ref: "main"
            
            - name: Printing Folders
              run: |
                echo "Printing all folders recursively"
                find . -type d
                echo "Completed printing."