name: 06 - Contexts
on:
    workflow_dispatch:
        inputs:
            debug:
                type: boolean
                default: false
run-name: My custom workflow run name - ${{ inputs.debug }}
env:
    MY_WORKFLOW_VAR: 'Workflow'
    MY_OVERWRITTEN_VAR: 'Workflow'    

jobs:
    echo-data:
        runs-on: ubuntu-latest
        env:
            MY_JOB_VAR: 'Job'
            MY_OVERWRITTEN_VAR: 'Job'
        steps:
            - name: Display information
              run: |
                echo "Event name : ${{ github.event_name }}"
                echo "Ref : ${{ github.ref_name }}"
                echo "SHA : ${{ github.sha }}"
                echo "Actor : ${{ github.actor }}"
                echo "Worflow : ${{ github.workflow }}"
                echo "Run ID: ${{ github.run_id }}"
                echo "Run Number: ${{ github.run_number }}"
            
            - name: Retrieve variable
              run: | 
                echo "Value of variable MY_VAR : ${{ vars.MY_VAR }} "
            
            - name: Print secret
              run: |
                echo "Value stored in MY_SECRET is ${{ secrets.MY_SECRET }}"    

            - name: Print env
              env:
                MY_OVERWRITTEN_VAR: 'Step'
              run: |
               echo "My var: ${{ env.MY_WORKFLOW_VAR }}"
               echo "My Job var : ${{ env.MY_JOB_VAR }}"
               echo "My overwritten var : ${{ env.MY_OVERWRITTEN_VAR }}"
               
            - name: Print env again
              run: |
                echo "My var: ${{ env.MY_WORKFLOW_VAR }}"
                echo "My Job var : ${{ env.MY_JOB_VAR }}"
                echo "My overwritten var : ${{ env.MY_OVERWRITTEN_VAR }}"
                